name: xformers

on: workflow_dispatch

jobs:
  build_wheels:
    name: Build xformers windows wheels
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
        with:
          repository: facebookresearch/xformers
          submodules: recursive

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - uses: Jimver/cuda-toolkit@v0.2.11
        id: cuda-toolkit
        with:
          cuda: "12.1.0"
          method: network
          use-github-cache: false

      - name: install build tools
        run: pip install -U ninja build wheel setuptools

      - name: install pytorch
        run: pip install torch==2.1.0+cu121 --index-url https://download.pytorch.org/whl/test/cu121

      - name: build wheel
        env:
          TORCH_CUDA_ARCH_LIST: "8.0;8.6+PTX;8.9;9.0"
        run: python -m build -n -w

      - name: upload wheel
        uses: actions/upload-artifact@v3
        with:
          name: xformers-${{ matrix.python-version }}
          path: dist
